language: "en-US"
early_access: false
reviews:
  profile: "chill"
  auto_title_placeholder: "@coderabbitai"
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true
