name: Manually Trigger Dependabot

on:
  workflow_dispatch:
    inputs:
      trigger-update:
        description: 'Trigger Dependabot updates'
        required: true
        default: 'true'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Trigger Dependabot manually via GitHub API
      - name: Trigger Dependabot update using GitHub API
        run: |
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"auto_merge":true}' \
            "https://api.github.com/repos/${{ github.repository }}/dispatches"

