name: Dependency Security Audit

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly
  workflow_dispatch:  # Allows manual trigger through GitHub CLI or GitHub UI

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: npm install
    - name: Run npm audit
      run: |
        npm audit --json > audit-report.json
        echo "## Dependency Vulnerabilities" > SECURITY.md
        cat audit-report.json | jq -r '.advisories | to_entries[] | "- \(.value.module_name): \(.value.severity) severity vulnerability"' >> SECURITY.md
      shell: bash
    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add SECURITY.md
        git commit -m "Update SECURITY.md with dependency audit results" || echo "No changes to commit"
        git push
