name: Manually Trigger Dependabot

on:
  workflow_dispatch:
    inputs:
      trigger-update:
        description: 'Trigger Dependabot updates'
        required: true
        default: 'true'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Trigger Dependabot updates using the GitHub API
      - name: Trigger Dependabot update
        uses: dependabot/fetch-metadata@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

